# Generated by Django 6.0.6 on 2026-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=150)),
                ('pdf_file', models.FileField(upload_to='subject_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
