# Generated by Django 6.0.4 on 2026-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectpdf',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
