# Generated by Django 6.0.6 on 2026-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subjectpdf_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectpdf',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
