# Generated by Django 6.0.6 on 2026-08-06 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subjectpdf_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
