# Generated by Django 6.0.6 on 2026-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pdfupload_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='subject',
            field=models.CharField(default='General', max_length=150),
        ),
    ]
