# Generated by Django 6.0.6 on 2026-08-20 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_favorite_unique_together_alter_favorite_paper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_paper_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectpdf'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'paper'), name='unique_user_favorite_paper'),
        ),
    ]
